import { BRAND_COACH_NAME } from '../branding.ts';

export type DisplayMessageData = {
  id: string;
  text: string;
  author: string | null;
};

function mentria(id: string, text: string): DisplayMessageData {
  return { id, text, author: 'Mentria' };
}

function pulse(id: string, text: string): DisplayMessageData {
  return { id, text, author: BRAND_COACH_NAME };
}

// Curated from the pinned Mentria Motivational Quotes dataset. See
// public/third-party-notices.txt for source revision and license details.
export const MOTIVATIONAL_MESSAGES: DisplayMessageData[] = [
  mentria('motivation-001', 'Water the work, not the worry.'),
  mentria('motivation-002', 'Keep one promise to yourself today, and tomorrow will trust you more.'),
  mentria('motivation-003', 'Rest like it is part of the plan, because it is.'),
  mentria('motivation-004', 'Count the attempts, not the misses; that ledger tells the truer story.'),
  mentria('motivation-005', 'Stack small wins until doubt cannot see over them.'),
  mentria('motivation-006', 'Aim at something far enough away that missing still lands you somewhere better.'),
  mentria('motivation-007', 'Stop rehearsing the disaster and start rehearsing the recovery.'),
  mentria('motivation-008', 'Sharpen the saw before you blame the tree.'),
  mentria('motivation-009', 'Hold your plans loosely and your standards tightly.'),
  mentria('motivation-010', 'Repair one small broken thing today; momentum is made of hinges.'),
  mentria('motivation-011', 'Compare notes, not lives.'),
  mentria('motivation-012', 'Bet on the slow compounding of ordinary days.'),
  mentria('motivation-013', 'Give your future self the gift of a decision made today.'),
  mentria('motivation-014', 'Trust the reps when the mirror shows nothing yet.'),
  mentria('motivation-015', 'Honor the plateau. Roots grow in the seasons when nothing shows above ground.'),
  mentria('motivation-016', 'Study your recoveries; they are more repeatable than your inspirations.'),
  mentria('motivation-017', 'Lower the bar for starting and raise it for stopping.'),
  mentria('motivation-018', 'What is the smallest brave thing you could do before lunch?'),
  mentria('motivation-019', 'What have you already survived that you keep forgetting to count?'),
  mentria('motivation-020', 'Begin again. That is the whole instruction.'),
  mentria('motivation-021', 'Done teaches. Perfect stalls.'),
  mentria('motivation-022', 'Your pace is not your worth.'),
  mentria('motivation-023', 'Direction first, velocity second.'),
  mentria('motivation-024', 'Small hinges swing heavy doors.'),
  mentria('motivation-025', 'Curiosity outlives certainty.'),
  mentria('motivation-026', 'Momentum forgives imperfect starts.'),
  mentria('motivation-027', 'A finished small thing beats a planned great one.'),
  mentria('motivation-028', 'Process is the only promise you control.'),
  mentria('motivation-029', 'Failure is data with feelings attached.'),
  mentria('motivation-030', 'Patience is ambition that learned to breathe.'),
  mentria('motivation-031', 'Beginnings are clumsy on purpose.'),
  mentria('motivation-032', 'You get remarkably strong lifting the same day over and over with intention.'),
  mentria('motivation-033', 'You will meet your potential only at the far end of many unremarkable Tuesdays.'),
  mentria('motivation-034', 'You grow in the direction of the questions you keep.'),
  mentria('motivation-035', 'You can bear the weight of any beginning for ten minutes; start with those.'),
  mentria('motivation-036', 'You water tomorrow every time you finish something small today.'),
  mentria('motivation-037', 'If the first step is too big, the step is wrong, not the dream.'),
  mentria('motivation-038', 'If motivation is weather, discipline is climate; build for climate.'),
  mentria('motivation-039', 'When the plan collapses, the purpose gets to speak.'),
  mentria('motivation-040', 'When you feel behind, look at whose clock you are reading.'),
  mentria('motivation-041', 'When you cannot lift the whole day, lift the next hour.'),
  mentria('motivation-042', 'If practice bores you, you are practicing the wrong size of challenge.'),
  mentria('motivation-043', 'If the door will not open, learn whether it is locked or merely heavy.'),
  mentria('motivation-044', 'When your hands learn a skill, your excuses lose a hiding place.'),
  mentria('motivation-045', 'Never confuse a resting season with a losing season.'),
  mentria('motivation-046', 'No skill was ever installed; every one was grown.'),
  mentria('motivation-047', 'Never mistake motion for meaning or stillness for surrender.'),
  mentria('motivation-048', 'Nothing you admire was made by someone who felt qualified at the start.'),
  mentria('motivation-049', 'To move fast, slow down where it counts.'),
  mentria('motivation-050', 'Hold on lightly and you can carry more.'),
  mentria('motivation-051', 'Confidence borrows; competence repays.'),
  mentria('motivation-052', 'Softness survives storms that stiffness cannot.'),
  mentria('motivation-053', 'To finish enormous things, be small and daily about them.'),
  mentria('motivation-054', 'Real urgency moves calmly.'),
  mentria('motivation-055', 'Doing less, but entirely, beats doing everything halfway.'),
  mentria('motivation-056', 'Rushing the harvest ruins the wine.'),
  mentria('motivation-057', 'Mastery looks like repetition from the outside and revelation from the inside.'),
  mentria('motivation-058', 'The obstacle is rarely the wall; it is the story about the wall.'),
  mentria('motivation-059', 'The plateau is where the roots drink.'),
  mentria('motivation-060', 'The best time to rest is slightly before you need to.'),
  mentria('motivation-061', 'The finish line moves; the starting line is always exactly where you stand.'),
  mentria('motivation-062', 'A skill is a promise your past kept to your present.'),
  mentria('motivation-063', 'A rested mind negotiates better with every fear.'),
  mentria('motivation-064', 'A crooked start still beats a straight excuse.'),
  mentria('motivation-065', 'Growth begins where explanations end and experiments begin.'),
  mentria('motivation-066', 'Progress hides inside routines the way rivers hide inside rain.'),
  mentria('motivation-067', 'Resilience is mostly memory: proof you have been here before and left alive.'),
  mentria('motivation-068', 'Motivation attends the launch party; discipline shows up for the night shifts.'),
  mentria('motivation-069', 'Doubt is not a stop sign; it is a request for evidence.'),
  mentria('motivation-070', 'Improvement loves specifics and starves on generalities.'),
  mentria('motivation-071', 'Time reveals which of your efforts were seeds and which were confetti.'),
  mentria('motivation-072', 'Mastery is patience arranged in rows.'),
  mentria('motivation-073', 'Freedom follows discipline around like a shadow follows light.'),
  mentria('motivation-074', 'Simplicity is the souvenir you bring back from complexity.'),
  mentria('motivation-075', 'Attention is love in its work clothes.'),
  mentria('motivation-076', 'Rest is a skill; collapse is its absence.'),
  mentria('motivation-077', 'Sourdough teaches what hustle forgets: some transformations only happen at rest.'),
  mentria('motivation-078', 'Glaciers carve valleys without ever exceeding walking pace.'),
  mentria('motivation-079', 'Tides retreat twice a day and nobody calls the ocean a quitter.'),
  mentria('motivation-080', 'Bamboo spends years building underground before its famous sprint to the sky.'),
  mentria('motivation-081', 'Stars navigate sailors who never touch them; be that kind of steady for someone.'),
  mentria('motivation-082', 'Migrating birds take turns breaking the wind; endurance is a team sport flown in shifts.'),
  mentria('motivation-083', 'Lanterns do not lecture the dark; they just refuse to join it.'),
  mentria('motivation-084', 'Seeds negotiate with stone every spring, and every spring some crack wins.'),
  mentria('motivation-085', 'Fireflies do not compete with the dark; they punctuate it.'),
  mentria('motivation-086', 'Perennials look dead all winter. Do not eulogize what is merely dormant, including yourself.'),
  mentria('motivation-087', 'Try the smaller brave thing first. Courage scales up faster than it starts up.'),
  mentria('motivation-088', 'Nobody warms up applauding themselves. Warm up anyway; the audience arrives later.'),
  mentria('motivation-089', 'Your heroes kept going without knowing they would become your heroes. Continue without the spoilers.'),
  mentria('motivation-090', 'Half of wisdom is learning what to ignore. The other half is remembering to practice the first half.'),
  mentria('motivation-091', 'Grand ambitions are shy. Feed them privacy and consistency, and they grow bold.'),
  mentria('motivation-092', 'Everyone wants the summit photo. Fall in love with switchbacks and the photo takes itself.'),
  mentria('motivation-093', 'Yesterday\'s ceiling makes a fine floor. Stack them long enough and you have built a staircase.'),
  mentria('motivation-094', 'Momentum is loyal. Feed it on Monday and it still shows up on Thursday.'),
  mentria('motivation-095', 'Ships log every league, even the boring ones. Log yours; averages tell kinder truths than moods.'),
  mentria('motivation-096', 'Everyone is self-taught at the final skill: continuing without supervision.'),
  mentria('motivation-097', 'Waiting for confidence before acting is like waiting for muscles before joining the gym.'),
  mentria('motivation-098', 'Rest is not the opposite of ambition; it is ambition\'s maintenance schedule.'),
  mentria('motivation-099', 'Being gentle with yourself on hard days is not lowering the bar; it is keeping the athlete healthy.'),
  mentria('motivation-100', 'Recovery days build champions as surely as training days; the muscle grows between the lifts.'),
  mentria('motivation-101', 'Speak to your tired self like a good coach, not a bad landlord.'),
  mentria('motivation-102', 'Track the streak, forgive the gap, resume the chain.'),
  mentria('motivation-103', 'Run your own race lane; clocks differ, finish lines differ, and the crowd is mostly imaginary.'),
  mentria('motivation-104', 'Measure yourself against your last draft, not their highlight reel.'),
  mentria('motivation-105', 'Courage is contagious in both directions: catch it from the brave, spread it to the hesitant.'),
  mentria('motivation-106', 'Bravery has a budget version: do it trembling.'),
  mentria('motivation-107', 'Nerves before the attempt are the body tuning its instruments.'),
  mentria('motivation-108', 'Risk shrinks when itemized and balloons when generalized.'),
  mentria('motivation-109', 'Beginnings forgive everything except their own absence.'),
  mentria('motivation-110', 'First attempts are down payments, not verdicts.'),
  mentria('motivation-111', 'Every expert\'s first version lives in a drawer, blushing.'),
  mentria('motivation-112', 'Starting badly is a genre, and every master has published in it.'),
  mentria('motivation-113', 'Day one keeps returning until you greet it properly.'),
  mentria('motivation-114', 'Motivation is a spark plug, not an engine.'),
  mentria('motivation-115', 'Habit is the loyal employee who works while inspiration takes its long lunches.'),
  mentria('motivation-116', 'Routines are rituals that stopped asking for applause.'),
  mentria('motivation-117', 'Bounce is a skill: fall small, land soft, rise informed.'),
  mentria('motivation-118', 'Celebrate small wins loudly enough that your brain learns which behaviors get parades.'),
  mentria('motivation-119', 'Consistency has no fan club, only results.'),
  mentria('motivation-120', 'Slow progress is still traffic moving.'),
];

// Workout-specific cooldown copy authored for Laptiva.
export const ASPIRATIONAL_MESSAGES: DisplayMessageData[] = [
  pulse('aspiration-001', 'Let your breathing settle. Notice what felt difficult, what became easier, and one small thing you want to carry into the next session.'),
  pulse('aspiration-002', 'The work is finished; the adaptation is beginning. Give your body time to slow down and acknowledge the effort you chose to make today.'),
  pulse('aspiration-003', 'Release the tension you no longer need. Keep the confidence that comes from completing one more deliberate practice.'),
  pulse('aspiration-004', 'Let your breath find a quieter rhythm. You do not need to rush recovery; this is part of the session.'),
  pulse('aspiration-005', 'Notice one moment when you wanted to stop and chose to continue. Keep that evidence for the next hard day.'),
  pulse('aspiration-006', 'Soften your shoulders and unclench your hands. Let the effort leave gradually while the accomplishment stays.'),
  pulse('aspiration-007', 'The timer is slowing down, but the value of the work remains. Give yourself a moment to recognize it.'),
  pulse('aspiration-008', 'Take inventory without judgment: your breath, your energy, and the effort you were able to give today.'),
  pulse('aspiration-009', 'A strong finish includes a thoughtful recovery. Let these final moments complete the work.'),
  pulse('aspiration-010', 'Let each breath mark the distance between the hardest part of the session and the calm returning now.'),
  pulse('aspiration-011', 'Your only task now is to slow down, breathe comfortably, and allow the session to come to a close.'),
  pulse('aspiration-012', 'The effort has already counted. There is nothing left to prove in these final moments.'),
  pulse('aspiration-013', 'Notice the difference between being tired and being defeated. You finished; let that distinction stay with you.'),
  pulse('aspiration-014', 'You made time to move with purpose today. That choice matters beyond the numbers on the timer.'),
  pulse('aspiration-015', 'Keep today\'s lesson simple: what helped, what challenged you, and what you want to repeat next time.'),
  pulse('aspiration-016', 'Let your posture soften as your breathing settles. Strength also includes knowing when to release effort.'),
  pulse('aspiration-017', 'This quiet is not empty. It holds every round, every restart, and every choice to keep going.'),
  pulse('aspiration-018', 'You did not need a perfect session to create progress. Showing up and finishing were enough for today.'),
  pulse('aspiration-019', 'Give the effort credit before you evaluate it. Reflection is clearer after acknowledgment.'),
  pulse('aspiration-020', 'Recovery is where the session becomes a memory you can learn from. Notice what you want to remember.'),
  pulse('aspiration-021', 'Feel your feet settle beneath you. Let your attention return from the timer to the room around you.'),
  pulse('aspiration-022', 'Thank the version of you who started this session. You carried that decision all the way through.'),
  pulse('aspiration-023', 'Progress is not measured only in speed or repetitions. It also lives in patience, control, and consistency.'),
  pulse('aspiration-024', 'You can be proud of the work without pretending it was easy. Both things can be true.'),
  pulse('aspiration-025', 'Let your breathing widen and your pace soften. The session is ending with intention, not simply stopping.'),
  pulse('aspiration-026', 'Acknowledge the discipline it took to begin, the effort it took to continue, and the calm it takes to recover.'),
  pulse('aspiration-027', 'Carry the confidence forward and leave the strain here. You have already taken what you need from this session.'),
  pulse('aspiration-028', 'Today\'s effort does not need comparison. It belongs to this body, this day, and this moment.'),
  pulse('aspiration-029', 'The session asked something of you, and you answered. Let that be enough as your breathing settles.'),
  pulse('aspiration-030', 'Notice the strength it took to begin and the patience it takes to finish slowly.'),
  pulse('aspiration-031', 'Slow down enough to hear what the workout taught you. The useful lesson is often a quiet one.'),
  pulse('aspiration-032', 'Let the cooldown close the workout cleanly. Keep the lesson, release the tension, and return refreshed.'),
  pulse('aspiration-033', 'Your body has done what you asked of it today. Respond with patience as the effort fades.'),
  pulse('aspiration-034', 'One completed session may feel small, but consistency is built from moments exactly like this one.'),
  pulse('aspiration-035', 'Use these final moments to notice what went well before deciding what you will improve.'),
  pulse('aspiration-036', 'Whatever pace brought you here, you completed the same promise: begin, continue, and recover.'),
  pulse('aspiration-037', 'The hardest seconds are behind you. Let your breath become easy and allow satisfaction to arrive.'),
  pulse('aspiration-038', 'Let satisfaction arrive without rushing past it. You earned a quiet moment at the end of the work.'),
  pulse('aspiration-039', 'This was practice in both effort and recovery. Each deserves your full attention.'),
  pulse('aspiration-040', 'End with the same intention you brought to the first round: present, steady, and ready to return another day.'),
];
